### Welcome to day 15 of 30 days of python

-- Numpy  
-- 1D array  
-- 2D array  
-- 3D array    
-- Indexing & Slicing 
-- Reshaping, Concatenation   

-- mean  
-- median  
-- standard deviation  
  
NumPy is a powerful library for numerical computations in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures efficiently.  

[Learn More about Numpy](https://numpy.org/devdocs/user/absolute_beginners.html)

What is array?

In computer programming, an array is a structure for storing and retrieving data.

Mini Project

Temperature Data Analysis
Generate random temperature data for 30 days and calculate the mean, median, and standard deviation of the temperature over the month. Also, find the days with temperatures above the average.

In [42]:
import numpy as np

In [43]:
np.__version__

'2.1.1'

In [44]:
type([1, 2, 3])

list

In [ ]:
0, 1,2,3, 5, 6

In [80]:
arr = np.array([0, 6, 5, 1, 2, 3])
type(arr)

numpy.ndarray

In [49]:
arr.shape

(3,)

In [55]:
print(np.std(arr))

2.1147629234082532


In [115]:
arr2d = np.array(
    [
        [5, 0, 4], 
        [2, 9, 6]
    ]
    )

arr2d.ndim


2

In [73]:
np.median(arr2d)

np.float64(3.0)

In [74]:
# slicing and indexing

In [85]:
arr_sorted = np.sort(arr)

In [83]:
# sorting

print(np.sort(arr)[2])


2


In [86]:
arr_sorted

array([0, 1, 2, 3, 5, 6])

In [88]:
print(arr_sorted[-1])

6


In [89]:
arr

array([0, 6, 5, 1, 2, 3])

In [90]:
arr_sorted

array([0, 1, 2, 3, 5, 6])

In [91]:
arr_sorted[-2:]

array([5, 6])

In [93]:
arr_sorted[4:5+1]

array([5, 6])

In [96]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [103]:
print(arr2d[0][2])

4


In [104]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [108]:
arr2d[1][1:]

array([7, 8])

In [116]:
np.sort(arr2d)

array([[0, 4, 5],
       [2, 6, 9]])

In [118]:
arr3d = np.array(
    [
    [[1, 2, 3],[3, 4, 6]],
    [[4, 5, 6],[5, 6, 8]]
    ]
    )

arr3d.ndim

3

In [125]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [121]:
x = np.array([
    [[], [], []], 
    [[], [], []], 
    [[], [], []]
])

x.ndim

3

In [119]:
arr3d

array([[[1, 2, 3],
        [3, 4, 6]],

       [[4, 5, 6],
        [5, 6, 8]]])

In [133]:
print(arr3d[1][1][-1])

8


In [142]:
arr3d[1][0][1:]

array([5, 6])

In [152]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.ndim

1

In [157]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
arr.reshape(2, 3, 1).ndim

3

In [174]:
arr1 = np.ones(5)
arr2 = np.zeros(5)

In [176]:
arr_con = np.concat((arr1, arr2))

In [177]:
arr_con.size

10